version: '3'
services:
  magic-decks:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data  # Persist les données sur l'hôte
    environment:
      - FLASK_ENV=development
